### ISSUE TITLE
select query returns extra columns of primary key

### ISSUE THREAD

**Issue by hqin** [SAP/go-ase#182]
**Description**

select query returns extra columns of primary key

**Expected behaviour**

select query should only return the columns specified in the query

**Current behaviour**

select query returns extra columns of primary key, in addition to the the columns specified.

**Steps to Reproduce**

Create two tables

```
 create table USER_ACCOUNT(user_id BIGINT not null, account_id varchar(32) not null, create_ts BIGINT not null, update_ts BIGINT not null)
 
 create table USER_ACCOUNT_WITH_PRIMARY_KEY(user_id BIGINT not null, account_id varchar(32) not null, create_ts BIGINT not null, update_ts BIGINT not null, primary key (user_id, account_id))
 ```
Run `go run coltypes.go` (with environment variables DB_USERNAME, DB_PASSWORD, DB_DATABASE, DB_PORT, and DB_DRIVER defined)

[coltypes.go.gz](https://github.com/SAP/go-ase/files/6132552/coltypes.go.gz)

You can see the extra columns being selected from USER_ACCOUNT_WITH_PRIMARY_KEY table:

```
Connected to database
Query: select create_ts  from USER_ACCOUNT
column[0]
	column name: create_ts
	type: ¿
	length = 0
scan type: interface {}
Query: select create_ts  from USER_ACCOUNT_WITH_PRIMARY_KEY
column[0]
	column name: create_ts
	type: ¿
	length = 0
scan type: interface {}
column[1]
	column name: user_id
	type: ¿
	length = 0
scan type: interface {}
column[2]
	column name: account_id
	type: ¯
	length = 64
scan type: interface {}
```

**Environment**

Client:
  OS: MacOS Big Sur 11.2.1
  go version: 1.16.0
  go-ase version / commit hash: github.com/SAP/go-ase v0.0.0-20210215075511-28ae8691af36
  go-dblib version / commit hash: github.com/SAP/go-dblib v0.0.0-20210215075453-57f65d7cdfe6

Server:
  OS: centos-7 
  ASE version: Adaptive Server Enterprise/16.0 SP03 PL09/EBF 29247 SMP/P/x86_64/SLES 11.1/ase1

**Comment by ntnn** [comment]
Hi @hqin,

#186 should fix the issue. Please reopen this issue if it doesn't.

Thanks
