### ISSUE TITLE
Error querying with "Order by"

### ISSUE THREAD

**Issue by adrianpozueco** [SAP/go-ase#183]
**Description**
In Ryanair we are using the driver and database/sql package to query a Sybase database and we are facing the issue, when we try to execute a query with "order by" clause we get the follow error message:
> "error querying: %!w(*fmt.wrapError=&{go-ase: error allocating cursor on server: error handling response to cursor opening: tds: error in user-defined processing function: unhandled package type *tds.OrderByPackage: tds.OrderByPackage(1): "

**Expected behaviour**

**Current behaviour**

A clear and concise description of what currently happens.

**Steps to Reproduce**

1. Execute any query like:
> SELECT top 30 legno_i, ac_registr, validity, departure_time, arrival_time, departure, arrival, tah/60 as 'tah', tac FROM dbo.ac_utilization WHERE ac_registr = 'APM' ORDER by validity
2. See error

**Environment**

Client:
  OS: Linux in AWS lambda
  go version: go 1.15
  go-ase version / commit hash: v0.0.0-20210129101534-7a9b97c65542
  go-dblib version / commit hash: SDK 1.15.1

Server:
  OS:
  ASE version: 16.0.03.08.1019

**Additional context**
Would be great any info about how to solve, also we are open to try to contribute if you provide us some hints about how to do it

**Comment by ntnn** [comment]
Hi @adrianpozueco,

#187 should fix the issue. Please reopen this issue if it doesn't.

Thanks
