### ISSUE TITLE
Getting error "expected TDS_MSG_SEC_ENCRYPT4, received: TDS_MSG_SEC_ENCRYPT3" while trying to connect to Sybase

### ISSUE THREAD

**Issue by RohitBinjola** [SAP/go-ase#190]
Code Used:

func main() {
	info, err := ase.NewInfo()
	info.Host = "<HostName>"
	info.Port = "<Port>"
	info.Username = "<UserName>"
	info.Password = "<Password>"
	info.Database = "<DatabaseName>"

	connector, err := ase.NewConnector(info)
	if err != nil {
		fmt.Println("Failed to create connector: %v", err)
		return
	}

	db := sql.OpenDB(connector)
	if err != nil {
		fmt.Println("Failed to open database: %v", err)
		return
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		fmt.Println("Failed to ping ASE: %v", err)
	}
}

Error Received: 
expected TDS_MSG_SEC_ENCRYPT4, received: TDS_MSG_SEC_ENCRYPT3

**Comment by ntnn** [comment]
Your ASE is either too old or not configured to support ODCE.
We only support communicating with ASEs using ODCE.

Please update or reconfigure your ASE.
