### ISSUE TITLE
TDS_MSG_SEC_ENCRYPT4 support

### ISSUE THREAD

**Issue by michaelhugi** [SAP/go-ase#202]
Not sure if I read this error message right:

```
error opening test connection: go-ase: error logging in: server only supports Extended Plus Encrypted Password login protocol, at least On Demand Command Encryption is required: expected TDS_MSG_SEC_ENCRYPT4, received TDS_MSG_SEC_ENCRYPT3
```

It seems that go-ase is using Encrypt3 but I can't figure out how to setup Encrypt4

Is this a bug or can you help me fix this on my system?

**Comment by ntnn** [comment]
Hi,

you need SAP ASE 16.0 SP03 or higher for ODCE / TDS_MSG_SEC_ENCRYPT4 to be available.

You can find details to this here: https://blogs.sap.com/2017/08/30/on-demand-encryption-in-sap-adaptive-server-enterprise/

Thanks
