### ISSUE TITLE
Nullable fields not handled correctly

### ISSUE THREAD

**Issue by hqin** [SAP/go-ase#203]
**Description**

Nullable fields not handled correctly.

**Expected behaviour**

Retrieving a null integer into sql.NullInt32 should have Valid field set to false

**Current behaviour**

Retrieving a null integer into sql.NullInt32 had Valid field set to true incorrectly

**Steps to Reproduce**

1. create sample table and populate data:
create table DATATYPE_INT_TEST(Id int primary key, IntFld int NULL, IntegerFld integer NULL,
   SmallintFld smallint NULL, TinyintFld tinyint NULL, BigintFld bigint NULL)
go
insert into DATATYPE_INT_TEST(Id, IntFld) values(2,2)
go

export environment variables DB_USERNAME, DB_PASSWORD, DB_DATABASE, DB_HOSTNAME, DB_PORT
2. Run the attached code using go-ase driver
DB_DRIVER=ase go run integer_validate.go
Connected to database using ase driver
select  IntFld, SmallintFld from DATATYPE_INT_TEST where Id=2
column[0]
	column name: IntFld
	type: INTN
	length = 4
	nullable = true
scan type: int64
column[1]
	column name: SmallintFld
	type: INTN
	length = 2
	nullable = true
scan type: int64
intFld: sql.NullInt32{Int32:2, Valid:true}, smallintFld: sql.NullInt32{Int32:0, Valid:true}

3. Run the attached code using tds driver
DB_DRIVER=tds go run integer_validate.go
Connected to database using tds driver
select  IntFld, SmallintFld from DATATYPE_INT_TEST where Id=2
column[0]
	column name: IntFld
	type: int
	nullable = true
scan type: int64
column[1]
	column name: SmallintFld
	type: smallint
	nullable = true
scan type: int64
intFld: sql.NullInt32{Int32:2, Valid:true}, smallintFld: sql.NullInt32{Int32:0, Valid:false}

**Environment**

Client:
  OS: centos-7
  go version: go1.16.3 linux/amd64
  go-ase version / commit hash:  v0.0.0-20210611100756-1778dda08c18
   
[integer_validate.go.gz](https://github.com/SAP/go-ase/files/6780460/integer_validate.go.gz)
go-dblib version / commit hash:  v0.0.0-20210610133137-f25b0f0fced0

Server:
  OS: centos-7
  ASE version: 16.0_SP03PL09_EBF29247

**Screenshots**

**Additional context**

**Comment by hqin** [comment]
Do we have an ETA on the fix?
I have written regression test on all data types, and it is shown that the issue is wide spread:
*  Unable to insert NULL fields
*  Unable to update fields to NULL values
*  Querying NULL values to sql.Null* type variables are not setting Valid field to false.

**Comment by cb80** [comment]
Dear hqin, your finding is highly appreciated and we are looking into it for a proper solution. However, there is no ETA. It simply takes the time it takes, especially during vacation times. Please also note that go-ase has not yet reached a v1 shape. So at the moment don’t rely on it for production. Stay tuned.

**Comment by benbjohnson** [comment]
I pushed up a change within `go-dblib` (https://github.com/SAP/go-dblib/pull/34) that I believe fixes the issue of querying NULL fields. It looks like the `goValue()` function should be returning `nil` values instead of `0`. I'm looking into the other types as well.

**Comment by fwilhelm92** [comment]
Solved in https://github.com/SAP/go-ase/pull/210
