### ISSUE TITLE
Need a way to represent nullable UNSIGNED BIGINT

### ISSUE THREAD

**Issue by hqin** [SAP/go-ase#205]
**Description**

There is no type in asetypes to represent nullable UNSIGNED BIGINT. database/sql has only sql.NullInt64

**Expected behaviour**

Need a type to represent nullable UNSIGNED BIGINT

**Current behaviour**

There is no type in asetypes to represent nullable UNSIGNED BIGINT.

**Steps to Reproduce**

**Environment**

Client:
  OS:
  go version:
  go-ase version / commit hash:
  go-dblib version / commit hash:

Server:
  OS:
  ASE version:

**Screenshots**

**Additional context**

**Comment by fwilhelm92** [comment]
Solved in https://github.com/SAP/go-ase/pull/210 (or respective https://github.com/SAP/go-dblib/pull/40)
