### ISSUE TITLE
Can't connect using sql.Open() and URI DSN

### ISSUE THREAD

**Issue by burningalchemist** [SAP/go-ase#237]
**Description**

Hi team, I cannot connect to the database using URI DSN via `database/sql` module, only Simple DSN is possible and passing parameters from the environment variables ([ref](https://github.com/SAP/go-ase/blob/414598c937a8a43c386bbb69f313a6d558e3b691/driver.go#L51-L67)).

**Expected behaviour**

The expected behaviour is that we can pass the supported URI DSN without any string manipulation directly to `sql.Open()` and connect to the database. Code-wise, it'd be great to have a similar control flow as in [here](https://github.com/SAP/go-dblib/blob/0afb096226b0ffe59e9d7c1fb3a3808d7db140ad/dsn/parse.go#L19-L25) in the `OpenConnector()` [function](https://github.com/SAP/go-ase/blob/414598c937a8a43c386bbb69f313a6d558e3b691/driver.go#L51). 

**Current behaviour**

Provided URI DSN string can't be parsed when passed to `sql.Open()` function, unless we explicitly call `dsn.Parse` [function](https://github.com/SAP/go-dblib/blob/0afb096226b0ffe59e9d7c1fb3a3808d7db140ad/dsn/parse.go#L19) that has the control flow to detect `://` and picks `ParseURI` function instead. This results in error:

```
Failed to open database: dsn: recognized DSN part does not contain key/value parts: [...]
```

The error comes from `parseSimple` [function](https://github.com/SAP/go-dblib/blob/0afb096226b0ffe59e9d7c1fb3a3808d7db140ad/dsn/parse.go#L138), which is not desired in my current use case.

**Steps to Reproduce**

Example from the README.md doesn't work:

```
package main

import (
    "database/sql"
    _ "github.com/SAP/go-ase"
)

func main() {
    db, err := sql.Open("ase", "ase://user:pass@host:port/")
    if err != nil {
        log.Printf("Failed to open database: %v", err)
        return
    }
    defer db.Close()

    if err := db.Ping(); err != nil {
        log.Printf("Failed to ping database: %v", err)
        return
    }
}
```

**Additional context**

I'm the maintainer of https://github.com/burningalchemist/sql_exporter project, and one of my users is experiencing issues connecting to the SAP ASE database. Since the project is database agnostic, we try to avoid adding custom handling for specific databases in order to keep the code small and simple.

**Comment by ntnn** [comment]
Hi, thanks for reporting this.

The problem is indeed odd as the entry function should be [Parse](https://github.com/SAP/go-dblib/blob/0afb096226b0ffe59e9d7c1fb3a3808d7db140ad/dsn/parse.go#L16-L25) which defers to `ParseSimple` when no `://` is in the passed string.

I'll see what I can find.

**Comment by ntnn** [comment]
Actually the error is pretty simple, go-ase [OpenConnector](https://github.com/SAP/go-ase/blob/414598c937a8a43c386bbb69f313a6d558e3b691/driver.go#L57) is calling `ParseSimple` directly instead of `Parse`.

I'm not entirely sure why `ParseSimple` why that was done but that is an easy fix.

**Comment by burningalchemist** [comment]
Perfect! Thanks a lot for the rapid fix! 🚀
