### ISSUE TITLE
Connection error with Sybase ASE 15.7

### ISSUE THREAD

**Issue by SoftExpert** [SAP/go-ase#240]
**Description**
I'm getting the following error when connecting to a Docker container created from https://hub.docker.com/r/ifnazar/sybase_15_7
```
error opening test connection: go-ase: error logging in: server only supports Extended Plus Encrypted Password login protocol, at least On Demand Command Encryption is required: expected TDS_MSG_SEC_ENCRYPT4, received TDS_MSG_SEC_ENCRYPT3
```
Any idea why this is happening ?

**Expected behaviour**

Connection is opened and no exception is returned.

**Current behaviour**

An exception is returned when opening the connection.

**Steps to Reproduce**

1. Write a test application that connects to the Sybase instance in the container on port 5000
```go
if db, err := sql.Open("ase", "ase://sa:password@localhost:5000/"); err != nil {
   panic(err)
}
```
3. Run the application
4. See the error

**Environment**

Client:
  OS: Linux, kernel 6.3.3
  go version: 1.20.4
  go-ase version / commit hash: v0.0.0-20230421120754-e9f4b4827fca
  go-dblib version / commit hash: v0.0.0-20230328101652-0afb096226b0

Server:
  OS: CentOS Linux release 7.2.1511 (Core)
  ASE version: Sybase ASE 15.7

**Comment by cb80** [comment]
15.7 is not supported by this driver. You need at least `SAP ASE 16.0 SP03`. Also see #202.
